FROM sonarqube:7.1-alpine
RUN cd $SONARQUBE_HOME/extensions/plugins 
ADD https://repox.sonarsource.com/sonarsource/org/sonarsource/go/sonar-go-plugin/1.1.0.1612/sonar-go-plugin-1.1.0.1612.jar $SONARQUBE_HOME/extensions/plugins/


